services:
  - type: web
    name: logitrack
    runtime: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn logitrack.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: logitrack.settings
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: logitrack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: logitrack-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: USE_S3
        value: "1"
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_REGION_NAME
        value: auto
      - key: AWS_S3_ENDPOINT_URL
        sync: false

  - type: worker
    name: logitrack-worker
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A logitrack worker --loglevel=info --concurrency=2"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: logitrack.settings
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        fromService:
          type: web
          name: logitrack
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: logitrack-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: logitrack-redis
          property: connectionString
      - key: USE_S3
        fromService:
          type: web
          name: logitrack
          envVarKey: USE_S3
      - key: AWS_STORAGE_BUCKET_NAME
        fromService:
          type: web
          name: logitrack
          envVarKey: AWS_STORAGE_BUCKET_NAME
      - key: AWS_ACCESS_KEY_ID
        fromService:
          type: web
          name: logitrack
          envVarKey: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
        fromService:
          type: web
          name: logitrack
          envVarKey: AWS_SECRET_ACCESS_KEY
      - key: AWS_S3_REGION_NAME
        fromService:
          type: web
          name: logitrack
          envVarKey: AWS_S3_REGION_NAME
      - key: AWS_S3_ENDPOINT_URL
        fromService:
          type: web
          name: logitrack
          envVarKey: AWS_S3_ENDPOINT_URL

databases:
  - name: logitrack-db
    databaseName: logitrack
    user: logitrack
    plan: free

  - type: redis
    name: logitrack-redis
    plan: free
    ipAllowList: []
