# Generated by Django 6.1.1 on 2026-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='distance_unit',
            field=models.CharField(default='miles', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='webhook_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(default='In-house fleet', max_length=80),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
