# Generated by Django 6.1.1 on 2026-10-06 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_profile_currency_profile_distance_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, max_length=64)),
                ('webhook_events', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pod/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_pin_raw',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('customer_unavailable', 'Customer Unavailable'), ('incorrect_address', 'Incorrect Address'), ('gate_locked', 'Gate / Access Code Required'), ('refused', 'Delivery Refused by Recipient'), ('damaged_in_transit', 'Package Damaged in Transit'), ('weather_delay', 'Severe Weather / Road Blockage'), ('business_closed', 'Business Closed'), ('other', 'Other Delivery Exception')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_signature',
            field=models.ImageField(blank=True, null=True, upload_to='pod/signatures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pod/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('customer_unavailable', 'Customer Unavailable'), ('incorrect_address', 'Incorrect Address'), ('gate_locked', 'Gate / Access Code Required'), ('refused', 'Delivery Refused by Recipient'), ('damaged_in_transit', 'Package Damaged in Transit'), ('weather_delay', 'Severe Weather / Road Blockage'), ('business_closed', 'Business Closed'), ('other', 'Other Delivery Exception')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='recipient_signature',
            field=models.ImageField(blank=True, null=True, upload_to='pod/signatures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='shipments.business'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.business'),
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('target_url', models.URLField()),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='success', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='shipments.business')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
