# Generated by Django 6.1.1 on 2026-10-06 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_business_profile_webhook_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='shipment-imports/%Y/%m/')),
                ('status', models.CharField(choices=[('queued', 'Queued for validation'), ('validating', 'Validating'), ('ready', 'Ready to import'), ('processing', 'Importing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invalid', 'Invalid'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_reference', ''), _negated=True), fields=('business', 'customer_reference'), name='uniq_shipment_business_customer_reference'),
        ),
        migrations.AddField(
            model_name='shipmentimportbatch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_imports', to='shipments.business'),
        ),
        migrations.AddField(
            model_name='shipmentimportbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentimportrow',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shipments.shipmentimportbatch'),
        ),
        migrations.AddField(
            model_name='shipmentimportrow',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='shipments.shipment'),
        ),
        migrations.AddConstraint(
            model_name='shipmentimportrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_import_batch_row_number'),
        ),
    ]
